##
# List from (http://userscripts.org/scripts/show/4175) converted to yaml and Base64Encoded.

--- 
YnV0Y2g=: 1
ZHlrZQ==: 1
cGh1a2tlZA==: 1
Yml0Y2hlcg==: 1
Y29ja3N1Y2tz: 1
ZnV4MHI=: 1
c2hpdGluZ3M=: 1
cG9ybm9ncmFwaHk=: 1
b3JnYXNt: 1
b3JnYXNpbQ==: 1
amVzdXMgaCBjaHJpc3Q=: 1
YnJvd24gZXll: 1
Y3VudGxpY2s=: 1
ZGluaw==: 1
YnV0dCBmdWNrZXI=: 1
Y3Vtcw==: 1
ZmlzdGZ1Y2tlcg==: 1
ZmFydA==: 1
ZnVja3M=: 1
c2xhZw==: 1
aml6eg==: 1
aG9va2Vy: 1
c2hpdHM=: 1
ZmFydGVk: 1
YmVsbHkgd2hhY2tlcg==: 1
YnJvd250b3du: 1
Y2xpdA==: 1
ZGlrZQ==: 1
bW90aGFmdWNrZXI=: 1
bW90aGFmdWNrYXo=: 1
Y3VudGxpY2tlcg==: 1
aG9ua2V5: 1
cGlzc2Vy: 1
aG9ybmllc3Q=: 1
Y29ja3N1Y2tpbmc=: 1
cGlzc2Vz: 1
bW90aGVyZnVja2luZw==: 1
bGVzYm8=: 1
c2xlYXpl: 1
YnVuZyBob2xl: 1
ZmVsbGF0aW8=: 1
ZmFydHk=: 1
ZnVrcw==: 1
cGlzc2lu: 1
cGh1aw==: 1
YnV0dCBicmVhdGg=: 1
cG9ybm9z: 1
bW90aGFmdWNr: 1
ZmVjZXM=: 1
amVzdXMgZnVja2luZyBjaHJpc3Q=: 1
dGl0cw==: 1
ZmFnb3Rz: 1
a3Vtcw==: 1
Z2FuZ2Jhbmc=: 1
ZmFnZ3M=: 1
ZWphY3VsYXRpbmc=: 1
ZWphY3VsYXRlZA==: 1
YnV0dGZhY2U=: 1
Y3VudHM=: 1
c2hpdHRlcg==: 1
c211dA==: 1
ZmF0YXNz: 1
c2NyZXc=: 1
bW90aGFmdWNrcw==: 1
a3VtbWluZw==: 1
ZmluZ2VyZnVja2Vy: 1
ZmluZ2VyZnVja2Vycw==: 1
d2V0YmFjaw==: 1
Yml0Y2hpbmc=: 1
YnV0dGZ1Y2s=: 1
Y3JhcA==: 1
cGh1a2tpbmc=: 1
bW90aGFmdWNrZWQ=: 1
YmFzdGFyZA==: 1
YnV0dCBoYWly: 1
Y3Vtc2hvdA==: 1
Y3liZXJmdWNr: 1
ZnVja21l: 1
ZnVja2Vycw==: 1
d3Rm: 1
bW90aGVyZnVja2Vk: 1
Yml0Y2g=: 1
Y3VuaWxpbmd1cw==: 1
ZG9uZw==: 1
ZnVja2luZ3M=: 1
cGh1a2Vk: 1
cHJpY2tz: 1
dmFnaW5h: 1
c2x1dHM=: 1
c2Nyb3R1bQ==: 1
b3JnYXNtcw==: 1
aG9ybnk=: 1
amFw: 1
dGl0dHk=: 1
Ymxvd2pvYnM=: 1
ZnVr: 1
ZmFncw==: 1
cmV0YXJk: 1
Y29vdGVy: 1
Y3VubmlsaW5ndXM=: 1
bW90aGFmdWNrYQ==: 1
cXVlZWY=: 1
YmxvdyBqb2I=: 1
cGVja2Vy: 1
c3B1bms=: 1
cHVzc2U=: 1
aG90c2V4: 1
bWFzdHVyYmF0ZQ==: 1
cGlzc2luZw==: 1
a29jaw==: 1
aGVsbA==: 1
ZmN1aw==: 1
bW90aGFmdWNraW5ncw==: 1
ZmlzdGZ1Y2s=: 1
cGh1a2luZw==: 1
YXNzZXM=: 1
bW90aGFmdWNraW5n: 1
aml6: 1
YXNzd2lwZQ==: 1
YnJvd25leWU=: 1
YXNzIGxpY2s=: 1
Y2xhbQ==: 1
a3Vr: 1
bmlnZ2Vy: 1
YmVzdGlhbGl0eQ==: 1
ZmlzdGZ1Y2tpbmdz: 1
c2hpdHR5: 1
cHVzc3lz: 1
cXdlZWY=: 1
ZmFydGluZ3M=: 1
ZmVsYXRpbw==: 1
a3Vt: 1
Y3VtbWluZw==: 1
dHdhdA==: 1
dGVzdGljbGVz: 1
bWljaw==: 1
Z2F6b25nZXJz: 1
YXNzaG9sZXM=: 1
Y29ja3N1Y2s=: 1
bW90aGVyZnVja2Vy: 1
Y29ja3N1Y2tlcg==: 1
aG9yZQ==: 1
ZmF0c28=: 1
YnVsbCBzaGl0: 1
Y2lyY2xlIGplcms=: 1
Y3liZXJmdWNrZXJz: 1
ZGljaw==: 1
ZmluZ2VyZnVja3M=: 1
aG9tbw==: 1
bW90aGVyZnVja2lu: 1
a2F3aw==: 1
Y29iaWE=: 1
Y29ja3M=: 1
Y3VuaWxsaW5ndXM=: 1
bXVmZg==: 1
c2hpdHRpbmdz: 1
cHIwbg==: 1
bHVzdGluZw==: 1
ZnVjaw==: 1
Z29vaw==: 1
aml6bQ==: 1
Z2F5: 1
b3JnYXNpbXM=: 1
cG9ybm8=: 1
bHVzdA==: 1
c3BpYw==: 1
YmVhc3RpYWw=: 1
YmVhc3RpYWxpdHk=: 1
Yml0Y2hlcnM=: 1
YnV0dGZ1Y2tlcg==: 1
ZmFnb3Q=: 1
YmVzdGlhbA==: 1
YnV0dGhvbGU=: 1
aGFyZCBvbg==: 1
ZmFydHM=: 1
cGltcA==: 1
Y2hpbms=: 1
ZGlwc2hpdA==: 1
ZmlzdGZ1Y2tlcnM=: 1
bWVyZGU=: 1
Y2xpdHM=: 1
c2hpdA==: 1
c25hdGNo: 1
amFja29mZg==: 1
ZnVja2Vk: 1
amFjayBvZmY=: 1
c2hpdGVk: 1
Y3VtbWVy: 1
cGh1Y2s=: 1
cHJpY2s=: 1
Zm9yZXNraW4=: 1
ZmluZ2VyZnVja2luZw==: 1
c2hlaXN0ZXI=: 1
bmlnZ2Vycw==: 1
bW90aGVyZnVjaw==: 1
YXNz: 1
ZGlsZG9z: 1
bmVyZA==: 1
aGFyZGNvcmVzZXg=: 1
amFjay1vZmY=: 1
ZWphY3VsYXRl: 1
ZGlua3M=: 1
ZnVja2luZw==: 1
cXVlZXI=: 1
bW91bmQ=: 1
a3JhdXQ=: 1
Z2F5c2V4: 1
d2Fuaw==: 1
d2hvYXI=: 1
c2hpdHRlZA==: 1
c2hpdHRlcnM=: 1
YmFsbHM=: 1
Y3VudA==: 1
amFja2Fzcw==: 1
a25vYg==: 1
amVyaw==: 1
bG9zZXI=: 1
bW90aGVyZnVja3M=: 1
a2lrZQ==: 1
YXNza2lzc2Vy: 1
ZHVtYmFzcw==: 1
a3VtbWVy: 1
d2hvcmU=: 1
bW90aGVyZnVja2Vycw==: 1
bW90aGFmdWNrZXJz: 1
Ym9uZWhlYWQ=: 1
Y3liZXJmdWM=: 1
cGh1a3M=: 1
bW90aGVyZnVja2luZ3M=: 1
dGl0dGllcw==: 1
c2hlbWFsZQ==: 1
cHVzc2llcw==: 1
ZWphY3VsYXRlcw==: 1
Y3Vt: 1
ZmlzdGZ1Y2tpbmc=: 1
ZmlzdGZ1Y2tlZA==: 1
cHVzc3k=: 1
YnV0dHBpY2tlcg==: 1
Y3liZXJmdWNraW5n: 1
aG9lcg==: 1
bmlnZ2E=: 1
bW90aGFmdWNrYXM=: 1
ZWphY3VsYXRpb24=: 1
c2x1dA==: 1
ZnU=: 1
Ymxvd2pvYg==: 1
Y3VudGxpY2tpbmc=: 1
ZmFnZ2V0: 1
cGlzcw==: 1
Z2FuZ2Jhbmdz: 1
c2hpeg==: 1
bGVzYmlhbg==: 1
Yml0Y2hlcw==: 1
dHdhdHk=: 1
ZWphY3VsYXRpbmdz: 1
c2hpdGluZw==: 1
Z29uYWRz: 1
amVyay1vZmY=: 1
YmVhdmVy: 1
ZmFydGluZw==: 1
c2hpdGZ1bGw=: 1
ZnVja2Vy: 1
cG9ybg==: 1
aDBy: 1
Y3liZXJmdWNrZXI=: 1
ZnVja2lu: 1
c2hpdHRpbmc=: 1
ZmVn: 1
Y2F3aw==: 1
ZG91Y2hlIGJhZw==: 1
cGlzc2Vycw==: 1
ZmFn: 1
ZmFnZ2l0: 1
ZmluZ2VyZnVjaw==: 1
d29w: 1
ZmFnZ290: 1
cGlzc2Vk: 1
a3Vrc3VnZXI=: 1
c2NobG9uZw==: 1
Y29jaw==: 1
bW90aGFmdWNraW4=: 1
Z3Vpbm5l: 1
ZmFnZ2luZw==: 1
ZnVyYnVyZ2Vy: 1
YnVt: 1
cGhvbmVzZXg=: 1
YmVhc3RpbGl0eQ==: 1
YnV0dA==: 1
ZGFtbg==: 1
aHVzc3k=: 1
Y29ja3N1Y2tlZA==: 1
a29uZHVtcw==: 1
cHJvc3RpdHV0ZQ==: 1
cGh1cQ==: 1
ZmlzdGZ1Y2tz: 1
cGVuaXM=: 1
YXNzaG9sZQ==: 1
YnVja2V0IGN1bnQ=: 1
YnVsbHNoaXQ=: 1
Y3liZXJmdWNrZWQ=: 1
a29uZHVt: 1
cGlzc29mZg==: 1
Yml0Y2hpbg==: 1
YnV0dGhlYWQ=: 1
ZmluZ2VyZnVja2Vk: 1
ZGlsZG8=: 1
Z2FuZ2JhbmdlZA==: 1
c2ghdA==: 1
amlzbQ==: 1
Ym9uZXI=: 1
a3VuaWxpbmd1cw==: 1
cHVuaw==: 1
amFja2luZyBvZmY=: 1
dGVldHM=: 1
Z29kZGFtbg==: 1
