:g:
  :rating:      G
  :heading:     General Audiences
  :info:        All ages admitted.

:pg:
  :rating:      PG
  :heading:     Parental Guidance Suggested
  :info:        Some material may not be suitable for children.

:pg_13:
  :rating:      PG-13
  :heading:     Parents Strongly Cautioned
  :info:        Some Material May Be Inappropriate for Children Under 13
  :description: Crude and sexual humor, language and a brief drug reference.

:r:
  :rating:      R
  :heading:     Restricted
  :info:        Under 17 requires accompanying parent or adult guardian.

:nc_17:
  :rating:      NC-17
  :heading:     No One 17 and Under Admitted
  :info:        Crude and sexual humor, language and a brief drug reference.
